/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        "surface-variant": "#e4e2e4",
        "secondary-container": "#708cfd",
        "on-secondary-fixed-variant": "#173bab",
        "on-background": "#1b1b1d",
        "on-tertiary-container": "#3980f4",
        "surface-dim": "#dcd9db",
        "surface-bright": "#fcf8fa",
        "primary-fixed": "#dae2fd",
        "on-surface-variant": "#45464d",
        "tertiary-container": "#001a42",
        "on-secondary-container": "#00217a",
        "inverse-surface": "#303032",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e4e2e4",
        "tertiary-fixed": "#d8e2ff",
        "outline": "#76777d",
        "on-tertiary-fixed": "#001a42",
        "inverse-on-surface": "#f3f0f2",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1b1d",
        "tertiary-fixed-dim": "#adc6ff",
        "surface-container-low": "#f6f3f5",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container": "#f0edef",
        "surface-tint": "#565e74",
        "primary": "#000000",
        "outline-variant": "#c6c6cd",
        "secondary-fixed-dim": "#b8c4ff",
        "tertiary": "#000000",
        "on-primary-container": "#7c839b",
        "primary-container": "#131b2e",
        "surface": "#fcf8fa",
        "secondary-fixed": "#dde1ff",
        "on-error": "#ffffff",
        "surface-container-high": "#eae7e9",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#004395",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#001453",
        "primary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "inverse-primary": "#bec6e0",
        "on-tertiary": "#ffffff",
        "secondary": "#3755c3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
      spacing: {
        "card-gap": "24px",
        "unit": "4px",
        "container-padding-desktop": "40px",
        "bento-radius": "24px",
        "container-padding-mobile": "16px"
      },
      fontFamily: {
        "data-mono": ["Geist"],
        "display-hero": ["Geist"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "headline-md": ["Geist"],
        "label-caps": ["Geist"]
      },
      fontSize: {
        "data-mono": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "500" }],
        "display-hero": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
