/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AccessibilityRouteImport } from "./routes/accessibility"
import { Route as CompleteRouteImport } from "./routes/complete"
import { Route as LanguageRouteImport } from "./routes/language"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as QueueRouteImport } from "./routes/queue"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as StaffRouteImport } from "./routes/staff"
import { Route as SymptomsRouteImport } from "./routes/symptoms"
import { Route as TicketRouteImport } from "./routes/ticket"
import { Route as TriageRouteImport } from "./routes/triage"
import { Route as StaffIndexRouteImport } from "./routes/staff.index"
import { Route as StaffAlertsRouteImport } from "./routes/staff.alerts"
import { Route as StaffAnalyticsRouteImport } from "./routes/staff.analytics"
import { Route as StaffDepartmentsRouteImport } from "./routes/staff.departments"
import { Route as StaffPatientsRouteImport } from "./routes/staff.patients"
import { Route as StaffQueueRouteImport } from "./routes/staff.queue"
import { Route as StaffPatientsIndexRouteImport } from "./routes/staff.patients.index"
import { Route as StaffPatientsPatientIdRouteImport } from "./routes/staff.patients.$patientId"
import { Route as StaffPatientsNewRouteImport } from "./routes/staff.patients.new"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: "/accessibility",
  path: "/accessibility",
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: "/complete",
  path: "/complete",
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: "/language",
  path: "/language",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: "/queue",
  path: "/queue",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: "/staff",
  path: "/staff",
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: "/symptoms",
  path: "/symptoms",
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: "/ticket",
  path: "/ticket",
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: "/triage",
  path: "/triage",
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => StaffRoute,
} as any)
const StaffAlertsRoute = StaffAlertsRouteImport.update({
  id: "/alerts",
  path: "/alerts",
  getParentRoute: () => StaffRoute,
} as any)
const StaffAnalyticsRoute = StaffAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => StaffRoute,
} as any)
const StaffDepartmentsRoute = StaffDepartmentsRouteImport.update({
  id: "/departments",
  path: "/departments",
  getParentRoute: () => StaffRoute,
} as any)
const StaffPatientsRoute = StaffPatientsRouteImport.update({
  id: "/patients",
  path: "/patients",
  getParentRoute: () => StaffRoute,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: "/queue",
  path: "/queue",
  getParentRoute: () => StaffRoute,
} as any)
const StaffPatientsIndexRoute = StaffPatientsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => StaffPatientsRoute,
} as any)
const StaffPatientsPatientIdRoute = StaffPatientsPatientIdRouteImport.update({
  id: "/$patientId",
  path: "/$patientId",
  getParentRoute: () => StaffPatientsRoute,
} as any)
const StaffPatientsNewRoute = StaffPatientsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => StaffPatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/accessibility": typeof AccessibilityRoute
  "/complete": typeof CompleteRoute
  "/language": typeof LanguageRoute
  "/login": typeof LoginRoute
  "/queue": typeof QueueRoute
  "/register": typeof RegisterRoute
  "/staff": typeof StaffRouteWithChildren
  "/symptoms": typeof SymptomsRoute
  "/ticket": typeof TicketRoute
  "/triage": typeof TriageRoute
  "/staff/alerts": typeof StaffAlertsRoute
  "/staff/analytics": typeof StaffAnalyticsRoute
  "/staff/departments": typeof StaffDepartmentsRoute
  "/staff/patients": typeof StaffPatientsRouteWithChildren
  "/staff/queue": typeof StaffQueueRoute
  "/staff/": typeof StaffIndexRoute
  "/staff/patients/$patientId": typeof StaffPatientsPatientIdRoute
  "/staff/patients/new": typeof StaffPatientsNewRoute
  "/staff/patients/": typeof StaffPatientsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/accessibility": typeof AccessibilityRoute
  "/complete": typeof CompleteRoute
  "/language": typeof LanguageRoute
  "/login": typeof LoginRoute
  "/queue": typeof QueueRoute
  "/register": typeof RegisterRoute
  "/symptoms": typeof SymptomsRoute
  "/ticket": typeof TicketRoute
  "/triage": typeof TriageRoute
  "/staff/alerts": typeof StaffAlertsRoute
  "/staff/analytics": typeof StaffAnalyticsRoute
  "/staff/departments": typeof StaffDepartmentsRoute
  "/staff/queue": typeof StaffQueueRoute
  "/staff": typeof StaffIndexRoute
  "/staff/patients/$patientId": typeof StaffPatientsPatientIdRoute
  "/staff/patients/new": typeof StaffPatientsNewRoute
  "/staff/patients": typeof StaffPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/accessibility": typeof AccessibilityRoute
  "/complete": typeof CompleteRoute
  "/language": typeof LanguageRoute
  "/login": typeof LoginRoute
  "/queue": typeof QueueRoute
  "/register": typeof RegisterRoute
  "/staff": typeof StaffRouteWithChildren
  "/symptoms": typeof SymptomsRoute
  "/ticket": typeof TicketRoute
  "/triage": typeof TriageRoute
  "/staff/alerts": typeof StaffAlertsRoute
  "/staff/analytics": typeof StaffAnalyticsRoute
  "/staff/departments": typeof StaffDepartmentsRoute
  "/staff/patients": typeof StaffPatientsRouteWithChildren
  "/staff/queue": typeof StaffQueueRoute
  "/staff/": typeof StaffIndexRoute
  "/staff/patients/$patientId": typeof StaffPatientsPatientIdRoute
  "/staff/patients/new": typeof StaffPatientsNewRoute
  "/staff/patients/": typeof StaffPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/accessibility"
    | "/complete"
    | "/language"
    | "/login"
    | "/queue"
    | "/register"
    | "/staff"
    | "/symptoms"
    | "/ticket"
    | "/triage"
    | "/staff/alerts"
    | "/staff/analytics"
    | "/staff/departments"
    | "/staff/patients"
    | "/staff/queue"
    | "/staff/"
    | "/staff/patients/$patientId"
    | "/staff/patients/new"
    | "/staff/patients/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/accessibility"
    | "/complete"
    | "/language"
    | "/login"
    | "/queue"
    | "/register"
    | "/symptoms"
    | "/ticket"
    | "/triage"
    | "/staff/alerts"
    | "/staff/analytics"
    | "/staff/departments"
    | "/staff/queue"
    | "/staff"
    | "/staff/patients/$patientId"
    | "/staff/patients/new"
    | "/staff/patients"
  id:
    | "__root__"
    | "/"
    | "/accessibility"
    | "/complete"
    | "/language"
    | "/login"
    | "/queue"
    | "/register"
    | "/staff"
    | "/symptoms"
    | "/ticket"
    | "/triage"
    | "/staff/alerts"
    | "/staff/analytics"
    | "/staff/departments"
    | "/staff/patients"
    | "/staff/queue"
    | "/staff/"
    | "/staff/patients/$patientId"
    | "/staff/patients/new"
    | "/staff/patients/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CompleteRoute: typeof CompleteRoute
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  QueueRoute: typeof QueueRoute
  RegisterRoute: typeof RegisterRoute
  StaffRoute: typeof StaffRouteWithChildren
  SymptomsRoute: typeof SymptomsRoute
  TicketRoute: typeof TicketRoute
  TriageRoute: typeof TriageRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accessibility": {
      id: "/accessibility"
      path: "/accessibility"
      fullPath: "/accessibility"
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/complete": {
      id: "/complete"
      path: "/complete"
      fullPath: "/complete"
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/language": {
      id: "/language"
      path: "/language"
      fullPath: "/language"
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/queue": {
      id: "/queue"
      path: "/queue"
      fullPath: "/queue"
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/staff": {
      id: "/staff"
      path: "/staff"
      fullPath: "/staff"
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/symptoms": {
      id: "/symptoms"
      path: "/symptoms"
      fullPath: "/symptoms"
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/ticket": {
      id: "/ticket"
      path: "/ticket"
      fullPath: "/ticket"
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/triage": {
      id: "/triage"
      path: "/triage"
      fullPath: "/triage"
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/staff/": {
      id: "/staff/"
      path: "/"
      fullPath: "/staff/"
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    "/staff/alerts": {
      id: "/staff/alerts"
      path: "/alerts"
      fullPath: "/staff/alerts"
      preLoaderRoute: typeof StaffAlertsRouteImport
      parentRoute: typeof StaffRoute
    }
    "/staff/analytics": {
      id: "/staff/analytics"
      path: "/analytics"
      fullPath: "/staff/analytics"
      preLoaderRoute: typeof StaffAnalyticsRouteImport
      parentRoute: typeof StaffRoute
    }
    "/staff/departments": {
      id: "/staff/departments"
      path: "/departments"
      fullPath: "/staff/departments"
      preLoaderRoute: typeof StaffDepartmentsRouteImport
      parentRoute: typeof StaffRoute
    }
    "/staff/patients": {
      id: "/staff/patients"
      path: "/patients"
      fullPath: "/staff/patients"
      preLoaderRoute: typeof StaffPatientsRouteImport
      parentRoute: typeof StaffRoute
    }
    "/staff/queue": {
      id: "/staff/queue"
      path: "/queue"
      fullPath: "/staff/queue"
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof StaffRoute
    }
    "/staff/patients/": {
      id: "/staff/patients/"
      path: "/"
      fullPath: "/staff/patients/"
      preLoaderRoute: typeof StaffPatientsIndexRouteImport
      parentRoute: typeof StaffPatientsRoute
    }
    "/staff/patients/$patientId": {
      id: "/staff/patients/$patientId"
      path: "/$patientId"
      fullPath: "/staff/patients/$patientId"
      preLoaderRoute: typeof StaffPatientsPatientIdRouteImport
      parentRoute: typeof StaffPatientsRoute
    }
    "/staff/patients/new": {
      id: "/staff/patients/new"
      path: "/new"
      fullPath: "/staff/patients/new"
      preLoaderRoute: typeof StaffPatientsNewRouteImport
      parentRoute: typeof StaffPatientsRoute
    }
  }
}

interface StaffPatientsRouteChildren {
  StaffPatientsPatientIdRoute: typeof StaffPatientsPatientIdRoute
  StaffPatientsNewRoute: typeof StaffPatientsNewRoute
  StaffPatientsIndexRoute: typeof StaffPatientsIndexRoute
}

const StaffPatientsRouteChildren: StaffPatientsRouteChildren = {
  StaffPatientsPatientIdRoute: StaffPatientsPatientIdRoute,
  StaffPatientsNewRoute: StaffPatientsNewRoute,
  StaffPatientsIndexRoute: StaffPatientsIndexRoute,
}

const StaffPatientsRouteWithChildren = StaffPatientsRoute._addFileChildren(
  StaffPatientsRouteChildren,
)

interface StaffRouteChildren {
  StaffAlertsRoute: typeof StaffAlertsRoute
  StaffAnalyticsRoute: typeof StaffAnalyticsRoute
  StaffDepartmentsRoute: typeof StaffDepartmentsRoute
  StaffPatientsRoute: typeof StaffPatientsRouteWithChildren
  StaffQueueRoute: typeof StaffQueueRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAlertsRoute: StaffAlertsRoute,
  StaffAnalyticsRoute: StaffAnalyticsRoute,
  StaffDepartmentsRoute: StaffDepartmentsRoute,
  StaffPatientsRoute: StaffPatientsRouteWithChildren,
  StaffQueueRoute: StaffQueueRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  CompleteRoute: CompleteRoute,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  QueueRoute: QueueRoute,
  RegisterRoute: RegisterRoute,
  StaffRoute: StaffRouteWithChildren,
  SymptomsRoute: SymptomsRoute,
  TicketRoute: TicketRoute,
  TriageRoute: TriageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
